DROP DATABASE ffinder_db;

CREATE DATABASE ffinder_db;

CREATE TABLE answers (
    id INT AUTO_INCREMENT NOT NULL,
    q1 TINYINT (1) NOT NULL,
    q2 TINYINT (1) NOT NULL,
    q3 TINYINT (1) NOT NULL,
    q4 TINYINT (1) NOT NULL,
    q5 TINYINT (1) NOT NULL,
    q6 TINYINT (1) NOT NULL,
    q7 TINYINT (1) NOT NULL,
    q8 TINYINT (1) NOT NULL,
    q9 TINYINT (1) NOT NULL,
    q10 TINYINT (1) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR (255) NOT NULL,
    photo VARCHAR (255) NULL, 
    PRIMARY KEY (id)
);

CREATE TABLE all (
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR (255) NOT NULL,
    photo VARCHAR (255) NULL, 
    q1 TINYINT (1) NOT NULL,
    q2 TINYINT (1) NOT NULL,
    q3 TINYINT (1) NOT NULL,
    q4 TINYINT (1) NOT NULL,
    q5 TINYINT (1) NOT NULL,
    q6 TINYINT (1) NOT NULL,
    q7 TINYINT (1) NOT NULL,
    q8 TINYINT (1) NOT NULL,
    q9 TINYINT (1) NOT NULL,
    q10 TINYINT (1) NOT NULL,
    PRIMARY KEY (id)
);
